# Generated by Django 4.1.7 on 2023-05-04 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'Strongly Dislike'), (1, 'Dislike'), (2, 'Unsure'), (3, 'Like'), (4, 'Strongly Like')])),
            ],
        ),
        migrations.CreateModel(
            name='intrests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest_name', models.CharField(max_length=50)),
                ('intrest_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=200)),
                ('questionType', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnet_location', models.CharField(blank=True, max_length=30)),
                ('student_college', models.CharField(blank=True, max_length=30)),
                ('student_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('student_answer', models.ManyToManyField(through='static_pages.Answer', to='static_pages.question')),
                ('student_intrest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='static_pages.intrests')),
                ('student_skill', models.ManyToManyField(to='static_pages.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answered_by',
            field=models.ManyToManyField(through='static_pages.Answer', to='static_pages.students'),
        ),
        migrations.CreateModel(
            name='occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=50)),
                ('occupation_description', models.CharField(max_length=50)),
                ('occupation_intrest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='static_pages.intrests')),
                ('ocuupation_skill', models.ManyToManyField(to='static_pages.skills')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('skill_id', models.ManyToManyField(to='static_pages.skills')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_pages.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_pages.students'),
        ),
    ]
