# Generated by Django 4.1.7 on 2023-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_intrest',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
