# Generated by Django 4.1.7 on 2023-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_intresttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='intresttest',
            name='question',
        ),
        migrations.AddField(
            model_name='intresttest',
            name='question',
            field=models.ManyToManyField(to='static_pages.question'),
        ),
    ]
