# Generated by Django 4.1.7 on 2023-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_students_password1_students_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password2',
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_description',
            field=models.TextField(),
        ),
    ]
