# Generated by Django 4.1.7 on 2023-04-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_question_remove_intresttest_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intresttest',
            name='answer',
            field=models.CharField(choices=[('strongly_dislike', 0), ('dislike', 1), ('unsure', 2), ('like', 3), ('strongly_like', 4)], default='unsure', max_length=20),
        ),
        migrations.AlterField(
            model_name='intresttest',
            name='question',
            field=models.ManyToManyField(blank=True, to='static_pages.question'),
        ),
    ]
