# Generated by Django 4.1.7 on 2023-04-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_intresttest_answer_alter_intresttest_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intresttest',
            name='answer',
            field=models.CharField(choices=[('strongly_dislike', 0), ('dislike', 1), ('unsure', 2), ('like', 3), ('strongly_like', 4)], max_length=20),
        ),
    ]
